package com.multipong.client;
import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'patriknygren' at '2016-11-27 20:06' with Gradle 2.13
 *
 * @author patriknygren, @date 2016-11-27 20:06
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
    }
}
